### ISSUE TITLE
Regarding using your code for different data set

### ISSUE THREAD

**Issue by wenouyang** [MarvinTeichmann/MediSeg#6]
Hi Marvin,

I have been trying to download `Segmentation_Rigid_Training.zip`, but it seems that the competition has ended, and I got no response from the data owner. Therefore, I just cannot run your program to get a more deep understanding on how does your code run?

My own data set has about 175 pairs of images in the form of `tif` file.  Each image is of size `580*720*1`, where `1` is the channel. 

In the `json` file, you have parameter setting as follows. I am not clear about what do `background_color` and `intrument_color `stand for; and how to modify them in the context of my own data set?  Besides changing the parameter in this json file, are there any other major modifications that I need to change in your code?

Thanks.

Wenouyang

> "data": {
>     "background_color" : [0],
>     "instrument_color" : [[70], [160]]
>   },
> 
>   "arch": {
>     "image_width": 640,
>     "image_height": 480,
>     "num_channels" : 3
>   },

**Comment by MarvinTeichmann** [comment]
Hi wenouyang,

yes, the authors of the Segmentation_Rigid_Training challenge are very slow to respond.

`Background color` and `instrument_color` describe how the class labels are encoded into the ground_truth. It is assumed, that the ground truth is given as image, where each class is corresponds to a pixel color. For a working example I would refer you once again to KittiSeg. There data can easily be downloaded and if you look at the ground_truth it is clear what is meant by `background_color`.

The code should work out of the box with you data, if you adjust the parameters you copied. I am not sure however, whether scipy is able to read `tif` our of the box. Otherwise you might consider to convert your data to `.png`.

In addition, you seam to have greyscale data. I would recommend loading the data as RGB using:

> image = scipy.misc.imread(image_file, mode='RGB')

Otherwise, you would need to adjust the VGG implementation, which expects 3 channel input.

**Comment by wenouyang** [comment]
Hi Marvin, thank you so much for the reply.  I have been planning to try KittiSeg, which seems to be based on Tensorflow 1.0 (is that right?). I am using Tensorflow 0.12.0-rc0. The development environment I am using is maintained through a centralized versional management system, I cannot update it until waiting certain period. So I am trying to try Mediseg at first, it seems to me Mediseg is based on an old Tensorflow version.

**Comment by MarvinTeichmann** [comment]
@wenouyang are you familiar with python `virtual_env`? It allows you to create a virtual environment in your home directory. In them, you can install any python package and you can easily switch between virtual environments and the main system. Is this an option?

(If virtualenv is not installed on you system, you can put it entire into your home e.g. by using `pip install virtualenv --user`)

**Comment by wenouyang** [comment]
Hi Marvin, thank you for your suggestion!
